# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TheQSaurus
                                 A QGIS plugin
 Vocabs integration into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-24
        copyright            : (C) 2025 by Brigit Danthine, Sinan Zülfikar
        email                : brigit.danthine@oeaw.ac.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TheQSaurus class from file TheQSaurus.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TheQSaurus import TheQSaurus
    return TheQSaurus(iface)
