# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TheQSaurus
                                 A QGIS plugin
 Vocabs integration into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Brigit Danthine, Sinan Zülfikar
        email                : brigit.danthine@oeaw.ac.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox 
from qgis.core import QgsWkbTypes, QgsMapLayerProxyModel

# Initialize Qt resources from file resources.py
from .resources_rc import *
# Import the code for the dialog
from .TheQSaurus_dialog import TheQSaurusDialog
import os.path
from qgis.utils import iface
from qgis.PyQt.QtWidgets import QAction, QTreeWidgetItem
from qgis.core import Qgis, QgsEditorWidgetSetup, QgsMapLayer, QgsMapLayerStyle, QgsMapLayerStyleManager
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QFileDialog

import os
import subprocess
import platform 
import sqlite3

from .csvhandler import * # regelt den csv import und Baumauflistung
from .ttlhandler import * # regelt alle Turtles auch die lokalen


class TheQSaurus:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'TheQSaurus_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&TheQSaurus')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('TheQSaurus', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/TheQSaurus/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'TheQSaurus'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&TheQSaurus'),
                action)
            self.iface.removeToolBarIcon(action)

    # WidgetTyp von gewählter Attributspalte wird auf WidgetType umgestellt
    def set_field_widget_type(self, layer, field_name, widget_type): 
        field_index = layer.fields().indexOf(field_name)
        if field_index == -1:
            self.iface.messageBar().pushWarning("TheQSaurus", f"Feld '{field_name}' nicht gefunden.")
            return

        config = {}
        widget_setup = QgsEditorWidgetSetup(widget_type, config)
        layer.setEditorWidgetSetup(field_index, widget_setup)
        layer.triggerRepaint()
        print(f"Widget-Typ von Feld '{field_name}' auf '{widget_type}' geändert.")

    # Ausgewählte Begriffe werden der Attributspalte hinzugefügt
    def set_value_map_widget(self, layer, field_name, value_map_dict): 
        field_index = layer.fields().indexOf(field_name)
        if field_index == -1:
            self.iface.messageBar().pushWarning("TheQSaurus", f"Feld '{field_name}' nicht gefunden.")
            return

        config = {
            'map': value_map_dict,
            'allowNull': True,  
            'useHtml': False  
        }

        widget_setup = QgsEditorWidgetSetup('ValueMap', config)
        layer.setEditorWidgetSetup(field_index, widget_setup)
        layer.triggerRepaint()
        print(f"ValueMap für Feld '{field_name}' gesetzt mit Werten: {value_map_dict}")


    # Befehle, die bei OK ausgeführt werden -> WidgetType ändern und mit Werten befüllen, Errorhandling falls Sachen nicht ausgwählt
    def on_ok_clicked(self):
        layer = self.dlg.eingabelayer.currentLayer()
        if not layer:
            self.iface.messageBar().pushWarning("TheQSaurus", "Kein Layer ausgewählt.")
            return

        field_name = self.dlg.eingabefeld.currentField()
        if not field_name:
            self.iface.messageBar().pushWarning("TheQSaurus", "Kein Feld ausgewählt.")
            return

        field_index = layer.fields().indexOf(field_name)
        if field_index == -1:
            self.iface.messageBar().pushWarning("TheQSaurus", f"Feld '{field_name}' nicht gefunden.")
            return

        selected_items = self.dlg.vocabsTree.selectedItems()
        if not selected_items:
            self.iface.messageBar().pushWarning("TheQSaurus", "Keine Auswahl getroffen.")
            return

        new_labels = [item.text(0) for item in selected_items]
        print("Neue Labels:", new_labels)

        # Werte an Widget übergeben
        # Aktuelle Widget-Konfiguration holen
        widget_setup = layer.editorWidgetSetup(field_index)
        config = widget_setup.config() if widget_setup.type() == "ValueMap" else {}

        # Alte ValueMap aus config holen oder neues dict
        old_value_map = config.get('map', {})

        # Neue Labels zu alten hinzufügen, ohne Duplikate
        for label in new_labels:
            if label not in old_value_map:
                old_value_map[label] = label

        # Aktualisierte ValueMap zurücksetzen
        self.set_value_map_widget(layer, field_name, old_value_map)
        self.iface.messageBar().pushMessage("TheQSaurus", "ValueMap erweitert.", level=Qgis.Success, duration=3)
        
        base_style_name = "qsaurus"

        # GPKG erkennen
        source = layer.dataProvider().dataSourceUri()
        path_part = source.split("|")[0]
        is_gpkg = path_part.lower().endswith(".gpkg")
        
        if is_gpkg and os.path.exists(path_part):
            # 1. Tabellenname (f_table_name) extrahieren
            table_name = None
            for part in source.split("|"):
                if part.startswith("layername="):
                    table_name = part.split("=")[1]
                    break
        
            if not table_name:
                print("⚠️ Tabellenname konnte nicht ermittelt werden!")
            else:
                print("🎯 Ziel-Tabellenname:", table_name)
        
                # 2. Styles im GPKG lesen
                conn = sqlite3.connect(path_part)
                cursor = conn.cursor()
        
                # Optional: sicherstellen, dass Tabelle existiert
                cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
                tables = [t[0] for t in cursor.fetchall()]
                if "layer_styles" not in tables:
                    print("ℹ️ Keine layer_styles-Tabelle gefunden. Stilname kann direkt verwendet werden.")
                    existing_style_names = []
                else:
                    cursor.execute("SELECT styleName FROM layer_styles WHERE f_table_name = ?", (table_name,))
                    existing_style_names = [row[0] for row in cursor.fetchall()]
                    print("🔍 Bereits vorhandene Style-Namen:", existing_style_names)
        
                conn.close()
                styles_before = set(existing_style_names)
        
                # 3. Neuen Stilnamen finden
                style_name = base_style_name
                counter = 1
                while style_name in existing_style_names:
                    style_name = f"{base_style_name}_{counter}"
                    counter += 1
        
                print("✅ Neuer Stilname:", style_name)
        
                # 4. Stil speichern
                success = layer.saveStyleToDatabase(
                    style_name,
                    '',  # Beschreibung
                    QgsMapLayer.StyleCategories(QgsMapLayer.StyleCategory.Forms),  # oder Forms, Symbology etc.
                    ''   # uiFileContent
                )
                
                conn = sqlite3.connect(path_part)
                cursor = conn.cursor()
                cursor.execute("SELECT styleName FROM layer_styles WHERE f_table_name = ?", (table_name,))
                styles_after = set(row[0] for row in cursor.fetchall())
                conn.close()
        
                if style_name in styles_after - styles_before:
                    self.iface.messageBar().pushMessage(f"✅ Stil '{style_name}' erfolgreich in GPKG gespeichert.", level=Qgis.Success, duration=3)
                    print(f"✅ Stil '{style_name}' erfolgreich in GPKG gespeichert.")
                else:
                    self.iface.messageBar().pushMessage("❌ Speichern des Stils fehlgeschlagen.", level=Qgis.Success, duration=3)
                    print("❌ Speichern des Stils fehlgeschlagen.")
        
        else:
            # Für Nicht-GPKG: Speicherpfad ermitteln
            layer_path = path_part
            directory = os.path.dirname(layer_path)
            base_filename = os.path.splitext(os.path.basename(layer_path))[0]
    
            style_filename = os.path.join(directory, f"{base_filename}_{base_style_name}.qml")
            counter = 1
            while os.path.exists(style_filename):
                style_filename = os.path.join(directory, f"{base_filename}_{base_style_name}_{counter}.qml")
                counter += 1
    
            # Speichern als .qml – nur "Forms"
            success = layer.saveNamedStyle(
                style_filename,
                QgsMapLayer.StyleCategories(QgsMapLayer.StyleCategory.Forms),
            )
    
            if not success:
                self.iface.messageBar().pushWarning("TheQSaurus", "Stil konnte nicht gespeichert werden.")
            else:
                self.iface.messageBar().pushMessage("TheQSaurus", f"Stil gespeichert unter {os.path.basename(style_filename)}.", level=Qgis.Success, duration=3)
    
    # Klick auf Checkbox Materialien
    def on_materialien_clicked(self):
        self.dlg.checkBox_Kulturepochen.blockSignals(True)
        self.dlg.checkBox_Kulturepochen.setChecked(False)
        self.dlg.checkBox_Kulturepochen.blockSignals(False)
        self.dlg.checkBox_customTurtleloader.blockSignals(True)
        self.dlg.checkBox_customTurtleloader.setChecked(False)
        self.dlg.checkBox_customTurtleloader.blockSignals(False)
        self.dlg.customTurtleLink.setEnabled(False)
        self.dlg.open_customTtlCsvPath.setEnabled(False)
        
        if self.dlg.checkBox_termsEnglish.isChecked():
            self.reload_graph_english("Materialien")
        else:
            self.reload_graph("Materialien")

    # Klick auf Checkbox Kulturepochen
    def on_kulturepochen_clicked(self):
        self.dlg.checkBox_Materialien.blockSignals(True)
        self.dlg.checkBox_Materialien.setChecked(False)
        self.dlg.checkBox_Materialien.blockSignals(False)
        self.dlg.checkBox_customTurtleloader.blockSignals(True)
        self.dlg.checkBox_customTurtleloader.setChecked(False)
        self.dlg.checkBox_customTurtleloader.blockSignals(False)
        self.dlg.customTurtleLink.setEnabled(False)
        self.dlg.open_customTtlCsvPath.setEnabled(False)

        if self.dlg.checkBox_termsEnglish.isChecked():
            self.reload_graph_english("Kulturepochen")
        else: 
            self.reload_graph("Kulturepochen")
        
    # Ladet den Thesaurusbaum
    def reload_graph(self, kategorie):
        g = load_graph(kategorie)  # Du musst ggf. load_graph() anpassen!
        if g is None:
            self.iface.messageBar().pushWarning("TheQSaurus", "Kein gültiger Vokabular-Layer geladen.")
            return

        extract_labels(g)
        roots = build_tree(g, lang_preference="de")

        tree = self.dlg.vocabsTree
        tree.clear()    
        tree.setColumnCount(1)
        tree.setHeaderLabels([self.tr(kategorie)])

        def add_items(parent_item, subtree_node):
            item = QTreeWidgetItem([subtree_node.name])
            parent_item.addChild(item)
            for child in subtree_node.children:
                add_items(item, child)

        for root in roots:
            top = QTreeWidgetItem([root.name])
            tree.addTopLevelItem(top)
            for child in root.children:
                add_items(top, child)
    
    # Ladet den Thesaurusbaum in Englisch
    def reload_graph_english(self, kategorie):
        g = load_graph(kategorie)  # Du musst ggf. load_graph() anpassen!
        if g is None:
            self.iface.messageBar().pushWarning("TheQSaurus", "Kein gültiger Vokabular-Layer geladen eng.")
            return

        extract_labels(g)
        roots = build_tree(g, lang_preference="en")

        tree = self.dlg.vocabsTree
        tree.clear()    
        tree.setColumnCount(1)
        tree.setHeaderLabels([self.tr(kategorie)])

        def add_items(parent_item, subtree_node):
            item = QTreeWidgetItem([subtree_node.name])
            parent_item.addChild(item)
            for child in subtree_node.children:
                add_items(item, child)

        for root in roots:
            top = QTreeWidgetItem([root.name])
            tree.addTopLevelItem(top)
            for child in root.children:
                add_items(top, child)

    # Expand and Colaps All Buttons
    def expand_tree_items(self):
        self.dlg.vocabsTree.expandAll()

    def collapse_tree_items(self):
        self.dlg.vocabsTree.collapseAll()

    # Custom link ttl
    def toggle_custom_link_input(self, checked):
        self.dlg.customTurtleLink.setEnabled(checked)
        self.dlg.open_customTtlCsvPath.setEnabled(checked)
        self.dlg.checkBox_Kulturepochen.blockSignals(True)
        self.dlg.checkBox_Kulturepochen.setChecked(False)
        self.dlg.checkBox_Kulturepochen.blockSignals(False)
        self.dlg.checkBox_Materialien.blockSignals(True)
        self.dlg.checkBox_Materialien.setChecked(False)
        self.dlg.checkBox_Materialien.blockSignals(False)

    # Suchfunktion
    def search_vocab_tree(self):
        search_text = self.dlg.searchLineEdit.text().strip().lower()
        if not search_text:
            self.iface.messageBar().pushWarning("TheQSaurus", "Bitte einen Suchbegriff eingeben.")
            return

        def search_items(item):
            match = False
            for i in range(item.childCount()):
                child = item.child(i)
                if search_items(child):
                    item.setExpanded(True)
                    match = True
            if search_text in item.text(0).lower():
                item.setBackground(0, QColor("yellow"))
                print(f"Treffer gefunden: {item.text(0)}")
                match = True
            else:
                item.setBackground(0, Qt.white)
            return match

        root_count = self.dlg.vocabsTree.topLevelItemCount()
        for i in range(root_count):
            top_item = self.dlg.vocabsTree.topLevelItem(i)
            search_items(top_item)

    # ladet das custom turtle
    def on_customttlbtn_clicked(self):
        turtle_data = self.dlg.customTurtleLink.toPlainText().strip()
        print(turtle_data)
        if not turtle_data:
            self.iface.messageBar().pushWarning("TheQSaurus", "Bitte eine Turtle-Datei auswählen.")
            return

        try:
            g = load_custom_graph(turtle_data)
        except Exception as e:
            self.iface.messageBar().pushWarning("TheQSaurus", f"Fehler beim Laden der Datei: {e}")
            return

        if g is None:
            self.iface.messageBar().pushWarning("TheQSaurus", "Turtle-Datei konnte nicht geladen werden.")
            return

        extract_labels(g)
        if self.dlg.checkBox_termsEnglish.isChecked():
            roots = build_tree(g, lang_preference="en")
        else: 
            roots = build_tree(g)
        #roots = build_tree(g, lang_preference="en")

        tree = self.dlg.vocabsTree
        tree.clear()
        tree.setColumnCount(1)
        tree.setHeaderLabels([self.tr("Custom Vocab")])

        def add_items(parent_item, subtree_node):
            item = QTreeWidgetItem([subtree_node.name])
            parent_item.addChild(item)
            for child in subtree_node.children:
                add_items(item, child)

        for root in roots:
            top = QTreeWidgetItem([root.name])
            tree.addTopLevelItem(top)
            for child in root.children:
                add_items(top, child)

        self.iface.messageBar().pushMessage("TheQSaurus", "Benutzerdefiniertes Vokabular geladen.", level=Qgis.Success, duration=3)

    # Turtle und csv-Dateien laden und 
    def on_load_local_clicked(self):
        path = self.dlg.open_customTtlCsvPath.filePath().strip()
        if not path:
            self.iface.messageBar().pushWarning("TheQSaurus", "Bitte eine Datei auswählen.")
            return
        
        if path.endswith(".ttl"):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    turtle_data = f.read()
            except Exception as e:
                self.iface.messageBar().pushWarning("TheQSaurus", f"Fehler beim Lesen der Datei: {e}")
                return

            g = load_custom_graph_from_text(turtle_data)

            if g is None:
                self.iface.messageBar().pushWarning("TheQSaurus", "Turtle-Datei konnte nicht geladen werden.")
                return

            extract_labels(g)
            roots = build_tree(g)

            tree = self.dlg.vocabsTree
            tree.clear()
            tree.setColumnCount(1)
            tree.setHeaderLabels([self.tr("Benutzerdefiniertes Vokabular")])

            def add_items(parent_item, subtree_node):
                item = QTreeWidgetItem([subtree_node.name])
                parent_item.addChild(item)
                for child in subtree_node.children:
                    add_items(item, child)

            for root in roots:
                top = QTreeWidgetItem([root.name])
                tree.addTopLevelItem(top)
                for child in root.children:
                    add_items(top, child)

            self.iface.messageBar().pushMessage("TheQSaurus", "Benutzerdefiniertes Vokabular (TTL) geladen.", level=Qgis.Success, duration=3)
        
        elif path.endswith(".csv"):
            try:
                print(f"Lade CSV von: {path}")
                load_csv_into_tree(path, self.dlg.vocabsTree)
                self.iface.messageBar().pushMessage("TheQSaurus", "CSV erfolgreich geladen.", level=Qgis.Success, duration=3)
            except Exception as e:
                self.iface.messageBar().pushWarning("TheQSaurus", f"Fehler beim Laden der CSV: {e}")
        else:
            self.iface.messageBar().pushWarning("TheQSaurus", "Dateiformat nicht unterstützt. Bitte eine .ttl oder .csv Datei auswählen.")

    def open_templates_folder(self):
        # Definiere hier den Pfad zu deinen Vorlagedateien
        folder_path = self.plugin_dir + "./templates"  # z. B. "/home/user/qgis_templates" oder "C:/Users/username/Documents/QGIS_Templates"
    
        # Prüfe, ob der Pfad existiert
        if not os.path.exists(folder_path):
            QMessageBox.warning(None, "Ordner nicht gefunden", f"Der Ordner '{folder_path}' existiert nicht.")
            return
    
        # Öffne den Ordner im Dateiexplorer je nach Betriebssystem
        system_platform = platform.system()
        try:
            if system_platform == "Windows":
                os.startfile(folder_path)
            elif system_platform == "Darwin":  # macOS
                subprocess.Popen(["open", folder_path])
            else:  # Linux und andere
                subprocess.Popen(["xdg-open", folder_path])
        except Exception as e:
            QMessageBox.critical(None, "Fehler", f"Ordner konnte nicht geöffnet werden:\n{str(e)}")

    def run(self):
        """Run method that performs all the real work"""
        
        self.dlg = TheQSaurusDialog()
        self.dlg.checkBox_Materialien.clicked.connect(self.on_materialien_clicked)
        self.dlg.checkBox_Kulturepochen.clicked.connect(self.on_kulturepochen_clicked)
        self.dlg.eingabelayer.setFilters(QgsMapLayerProxyModel.VectorLayer)
        self.dlg.eingabelayer.layerChanged.connect(self.dlg.eingabefeld.setLayer)
        self.dlg.begriffeLaden.clicked.connect(self.on_ok_clicked)
        self.dlg.expandAllbtn.clicked.connect(self.expand_tree_items)
        self.dlg.collapseAllbtn.clicked.connect(self.collapse_tree_items)
        self.dlg.checkBox_customTurtleloader.toggled.connect(self.toggle_custom_link_input)
        self.dlg.customttlbtn.clicked.connect(self.on_customttlbtn_clicked)
        self.dlg.searchBtn.clicked.connect(self.search_vocab_tree)
        self.dlg.loadLocalBtn.clicked.connect(self.on_load_local_clicked)

        self.dlg.customTurtleLink.setEnabled(False)
        self.dlg.checkBox_Kulturepochen.setChecked(True)
        self.dlg.open_customTtlCsvPath.setEnabled(False)
        
        self.dlg.open_customTtlCsvPath.lineEdit().setPlaceholderText("Bitte .ttl oder .csv Datei auswählen")

        self.dlg.open_customTtlCsvPath.setFilter("CSV- und Turtle-Dateien (*.csv *.ttl);;CSV-Dateien (*.csv);;Turtle-Dateien (*.ttl)")
        
        self.dlg.templates.clicked.connect(self.open_templates_folder)
        
        g = load_graph("Kulturepochen")
        if g is None:
            self.iface.messageBar().pushWarning("TheQSaurus", "Kein gültiger Vokabular-Layer geladen.")
            return
        extract_labels(g)
        roots = build_tree(g)
        
        tree = self.dlg.vocabsTree
        tree.clear()
        tree.setColumnCount(1)
        tree.setHeaderLabels([self.tr("Kulturepochen")])

        def add_items(parent_item, subtree_node):
            item = QTreeWidgetItem([subtree_node.name])
            parent_item.addChild(item)
            for child in subtree_node.children:
                add_items(item, child)

        for root in roots:
            top = QTreeWidgetItem([root.name])
            tree.addTopLevelItem(top)
            for child in root.children:
                add_items(top, child)
                
        self.dlg.show()
        result = self.dlg.exec_()

        if result:
            pass