# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TheQSaurusDialog
                                 A QGIS plugin
 Vocabs integration into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Brigit Danthine, Sinan Zülfikar
        email                : brigit.danthine@oeaw.ac.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'TheQSaurus_dialog_base.ui'))


class TheQSaurusDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TheQSaurusDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


        """
        self.checkBox_Materialien.toggled.connect(self.on_checkbox_toggled)
        self.checkBox_Kulturepochen.toggled.connect(self.on_checkbox_toggled)
        self.load_and_update_graph()

    def on_materialien_clicked(self):
        self.checkBox_Kulturepochen.blockSignals(True)
        self.checkBox_Kulturepochen.setChecked(False)
        self.checkBox_Kulturepochen.blockSignals(False)
        print("Materialien ist aktiviert")
        self.load_and_update_graph()

    def on_kulturepochen_clicked(self):
        self.checkBox_Materialien.blockSignals(True)
        self.checkBox_Materialien.setChecked(False)
        self.checkBox_Materialien.blockSignals(False)
        print("Kulturepochen ist aktiviert")
        self.load_and_update_graph()

    def load_and_update_graph(self):
        graph = load_graph(self)
        if graph is not None:
            print(f"Graph geladen mit {len(graph)} Tripeln")
        else:
            print("Kein Graph geladen")

    def on_checkbox_toggled(self, checked):
        if checked:
            sender = self.sender()

            if sender == self.checkBox_Materialien:
                self.checkBox_Kulturepochen.blockSignals(True)
                self.checkBox_Kulturepochen.setChecked(False)
                self.checkBox_Kulturepochen.blockSignals(False)

            elif sender == self.checkBox_Kulturepochen:
                self.checkBox_Materialien.blockSignals(True)
                self.checkBox_Materialien.setChecked(False)
                self.checkBox_Materialien.blockSignals(False)

            self.load_and_update_graph()
"""